In [6]:
import pandas as pd

df = pd.read_csv("salaries_by_college_major.csv")

In [12]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [8]:
df.shape

(51, 6)

In [9]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='str')

In [13]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [ ]:
clean_df = df.dropna()

In [15]:
clean_df.shape

(50, 6)

In [16]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [21]:
# find college major with highest starting salaries 

clean_df['Starting Median Salary'].idxmax()

43

In [24]:
# clean_df['Undergraduate Major'].loc[43]
clean_df['Undergraduate Major'][43]

'Physician Assistant'

In [37]:
# College with the highest Mid Career Median Salary

pos = clean_df['Mid-Career Median Salary'].idxmax()
the_major = clean_df['Undergraduate Major'][pos]
max_salary = clean_df['Mid-Career Median Salary'].max()

print(f"{the_major} has the highest median salary which amounts to: {max_salary}")

Chemical Engineering has the highest median salary which amounts to: 107000.0

In [38]:
min_pos = clean_df['Starting Median Salary'].idxmin()
the_min_major = clean_df['Undergraduate Major'][min_pos]
min_salary = clean_df['Starting Median Salary'].min()

print(f"{the_min_major} has the minimum starting salary which amounts to: {min_salary}")

Spanish has the minimum starting salary which amounts to: 34000.0

In [41]:
low_mid_salary_pos = clean_df["Mid-Career Median Salary"].idxmin()
the_mid_low_major = clean_df['Undergraduate Major'][low_mid_salary_pos]
low_mid_salary_amt = clean_df['Mid-Career Median Salary'].min()

print(f"The college major that has the lowest mid-career salary is {the_mid_low_major} and the amount is: {low_mid_salary_amt}")

The college major that has the lowest mid-career salary is Education and the amount is: 52000.0