In [25]:
import pandas as pd

df = pd.read_csv("salaries_by_college_major.csv")

pd.options.display.float_format = '{:,.2f}'.format

In [26]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"41,600.00","76,800.00","50,600.00","136,000.00",Business

In [27]:
df.shape

(51, 6)

In [28]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='str')

In [29]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [30]:
clean_df = df.dropna()

In [31]:
clean_df.shape

(50, 6)

In [32]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,"40,800.00","78,200.00","41,200.00","168,000.00",HASS
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS

In [33]:
# find college major with highest starting salaries 

clean_df['Starting Median Salary'].idxmax()

43

In [34]:
# clean_df['Undergraduate Major'].loc[43]
clean_df['Undergraduate Major'][43]

'Physician Assistant'

In [35]:
# College with the highest Mid Career Median Salary

pos = clean_df['Mid-Career Median Salary'].idxmax()
the_major = clean_df['Undergraduate Major'][pos]
max_salary = clean_df['Mid-Career Median Salary'].max()

print(f"{the_major} has the highest median salary which amounts to: {max_salary}")

Chemical Engineering has the highest median salary which amounts to: 107000.0

In [36]:
min_pos = clean_df['Starting Median Salary'].idxmin()
the_min_major = clean_df['Undergraduate Major'][min_pos]
min_salary = clean_df['Starting Median Salary'].min()

print(f"{the_min_major} has the minimum starting salary which amounts to: {min_salary}")

Spanish has the minimum starting salary which amounts to: 34000.0

In [37]:
low_mid_salary_pos = clean_df["Mid-Career Median Salary"].idxmin()
the_mid_low_major = clean_df['Undergraduate Major'][low_mid_salary_pos]
low_mid_salary_amt = clean_df['Mid-Career Median Salary'].min()

print(f"The college major that has the lowest mid-career salary is {the_mid_low_major} and the amount is: {low_mid_salary_amt}")

The college major that has the lowest mid-career salary is Education and the amount is: 52000.0

In [38]:
# diff between mid career 90th and 10th percentile salary

spread_mid_10th_90th = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

In [39]:
spread_mid_10th_90th.head()

0   109,800.00
1    96,700.00
2   113,700.00
3   104,200.00
4    85,400.00
dtype: float64

In [40]:
clean_df.insert(6, 'spread_mid_10th_90th', spread_mid_10th_90th)

In [41]:
clean_df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,spread_mid_10th_90th
0,Accounting,"46,000.00","77,100.00","42,200.00","152,000.00",Business,"109,800.00"
1,Aerospace Engineering,"57,700.00","101,000.00","64,300.00","161,000.00",STEM,"96,700.00"
2,Agriculture,"42,600.00","71,900.00","36,300.00","150,000.00",Business,"113,700.00"
3,Anthropology,"36,800.00","61,500.00","33,800.00","138,000.00",HASS,"104,200.00"
4,Architecture,"41,600.00","76,800.00","50,600.00","136,000.00",Business,"85,400.00"

In [42]:
sorted_data_by_spread = clean_df.sort_values('spread_mid_10th_90th', ascending=True)
sorted_data_by_spread[['Undergraduate Major', 'spread_mid_10th_90th']].head()

           Undergraduate Major  spread_mid_10th_90th
40                     Nursing             50,700.00
43         Physician Assistant             57,600.00
41                   Nutrition             65,300.00
49                     Spanish             65,400.00
27  Health Care Administration             66,400.00

In [43]:
top_5_90th = clean_df['Mid-Career 90th Percentile Salary'].sort_values(ascending=False).head()

In [44]:
top_5_90th

17   210,000.00
22   195,000.00
8    194,000.00
37   183,000.00
44   178,000.00
Name: Mid-Career 90th Percentile Salary, dtype: float64

In [45]:
clean_df.loc[[17, 22, 8, 37, 44], ['Undergraduate Major', 'Mid-Career 90th Percentile Salary']]

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                         210,000.00
22               Finance                         195,000.00
8   Chemical Engineering                         194,000.00
37                  Math                         183,000.00
44               Physics                         178,000.00

In [46]:
# low_risk['spread_mid_10th_90th'].tail()
sorted_data_by_spread['spread_mid_10th_90th'].tail()
sorted_data_by_spread.sort_values('spread_mid_10th_90th', ascending=False).head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,spread_mid_10th_90th
17,Economics,"50,100.00","98,600.00","50,600.00","210,000.00",Business,"159,400.00"
22,Finance,"47,900.00","88,300.00","47,200.00","195,000.00",Business,"147,800.00"
37,Math,"45,400.00","92,400.00","45,200.00","183,000.00",STEM,"137,800.00"
36,Marketing,"40,800.00","79,600.00","42,100.00","175,000.00",Business,"132,900.00"
42,Philosophy,"39,900.00","81,200.00","35,500.00","168,000.00",HASS,"132,500.00"

In [47]:
clean_df.groupby('Group').count()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,spread_mid_10th_90th
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [48]:
clean_df.groupby('Group').mean(numeric_only=True)

,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,spread_mid_10th_90th
Group,,,,,
Business,"44,633.33","75,083.33","43,566.67","147,525.00","103,958.33"
HASS,"37,186.36","62,968.18","34,145.45","129,363.64","95,218.18"
STEM,"53,862.50","90,812.50","56,025.00","157,625.00","101,600.00"